from pydantic import BaseModel, Field
from enum import Enum
from fastapi import Query
# ----------------------------------------------------------------------
# Base Models
# ----------------------------------------------------------------------
class MetricBaseModel(BaseModel):
    currency: str = Field("USD", description="Currency used in the calculations.")

# ----------------------------------------------------------------------
# Schemas for KPI Summary Endpoint
# ----------------------------------------------------------------------
class KPIsSummary(MetricBaseModel):
    total_revenue: float = Field(..., description="Total revenue generated.")
    total_products_sold: int = Field(..., description="Total number of products sold.")
    average_total_products_sold: float = Field(..., description="Average number of products sold.")

# ----------------------------------------------------------------------
# Schemas and Dependencies for Time Series Endpoint
# ----------------------------------------------------------------------
class Serie(MetricBaseModel):
    period: str = Field(..., description="Period of the data in YYYY-MM-DD (year-month-day)")
    revenue: float = Field(..., description="Revenue generated in the period.")
    products_sold: int = Field(..., description="Number of products sold in the period.")
    growth_rate: float = Field(..., description="Growth rate of the revenue compared to the previous period.")

class SerieType(str, Enum):
    MONTH = "month"
    WEEK = "week"
    YEAR = "year"
    DAY = "day"
    
    def get_resample_kind(self) -> str:
        match self.value:
            case "month":
                return "ME"
            case "week":
                return "W"
            case "year":
                return "Y"
            case "day":
                return "D"

def get_series_params(serie_type: SerieType = Query(SerieType.MONTH, description="Type of the series")) -> SerieType:
    return serie_type

# ----------------------------------------------------------------------
# Schemas and Dependencies for Top Countries Endpoint
# ----------------------------------------------------------------------
class TopCountryRevenue(MetricBaseModel):
    country: str = Field(..., description="Country name.")
    revenue: float = Field(..., description="Revenue generated in the country.")
    products_sold: int = Field(..., description="Number of products sold in the country.")

class SortValue(str, Enum):
    REVENUE = "revenue"
    PRODUCTS_SOLD = "products_sold"
    
class TopCountryRevenueParams(BaseModel):
    limit: int = Field(10, description="Number of countries to return.")
    ascending: bool = Field(False, description="Sort in ascending order.")
    sort_value: SortValue = Field(SortValue.REVENUE, description="Field to sort by.")
    
def get_top_countries_params(limit: int = Query(10, description="Number of countries to return."), 
                             ascending: bool = Query(False, description="Sort in ascending order by sort value."), 
                             sort_value: SortValue = Query(SortValue.REVENUE, description="Field to sort by.")
                             )-> TopCountryRevenueParams:
    return TopCountryRevenueParams(
        limit=limit,
        ascending=ascending,
        sort_value=sort_value
    )

# ----------------------------------------------------------------------
# /metrics/products/top-sellers Endpoint Schemas
# ----------------------------------------------------------------------

class Product(MetricBaseModel):
    product_id: str = Field(..., description="Unique identifier for the product.")
    product_description: str = Field(..., description="Description of the product.")
    total_revenue: float = Field(..., description="Total revenue generated by the product.")
    total_units_sold: int = Field(..., description="Total units sold of the product.")

class ProductsSortBy(str, Enum):
    REVENUE = "revenue"
    UNITS_SOLD = "units_sold"

class ProductMetricsParams(BaseModel):
    limit: int = Field(10, description="Number of top products to return.")
    ascending: bool = Field(False, description="Sort in ascending order.")
    sort_by: ProductsSortBy = Field(ProductsSortBy.REVENUE, description="Field to sort by.")

# ----------------------------------------------------------------------
# /metrics/customers/top-spenders Endpoint Schemas
# ----------------------------------------------------------------------
class Spender(BaseModel):
    customer_id: str = Field(..., description="Unique identifier for the customer.")
    total_spent: float = Field(..., description="Total amount spent by the customer.")
    total_sells: int = Field(..., description="Total number of sells by the customer.")
    total_units_sold: int = Field(..., description="Total number of units sold by the customer.")


class TopSpendersMetricsParams(BaseModel):
    limit: int = Field(10, description="Number of top spenders to return.")
    ascending: bool = Field(False, description="Sort in ascending order.")
    
def get_top_spenders_params(limit: int = Query(10, description="Number of top spenders to return."),
                            ascending: bool = Query(False, description="Sort in ascending order.")
                            ) -> TopSpendersMetricsParams:
    return TopSpendersMetricsParams(
        limit=limit,
        ascending=ascending
    )

def get_default_top_spenders_params() -> TopSpendersMetricsParams:
    return TopSpendersMetricsParams()

# ----------------------------------------------------------------------
# /metrics/customers/rfm Endpoint Schemas
# ----------------------------------------------------------------------   
class SegmentName(str, Enum):
    # high value clients
    CHAMPIONS = "Champion"
    LOYALTIES = "Loyalty"
    
    # spenders who need urgencily re-activation
    ALMOST_LOST = "Almost Lost" 
    EN_RISK = "In Risk"
    NEED_ATTENTION = "Need Atention" 
    
    # Low value clients or new clients 
    RECENTS = "Recent" 
    SLEEPER = "Sleeper"


class RFMAnalysis(BaseModel):
    recency: int = Field(..., description="Number of days since the last purchase.")
    frequency: int = Field(..., description="Number of purchases made.")
    monetary: float = Field(..., description="Total amount spent.")
    segment_name: SegmentName = Field(..., description="Customer segment based on RFM analysis.")
    total_spend: float = Field(..., description="Total amount spent by the customer.")